import { useState, useCallback } from "react";

const ALL = [
  // ── PRINCIPIANTE ──
  {name:"Fireman Spin",cat:"Spin",level:"beg",desc:"Avvolgi le gambe intorno al palo e lasciati girare con il corpo lungo e le braccia tese.",tip:"Tieni il core attivo per una rotazione pulita."},
  {name:"Chair Spin",cat:"Spin",level:"beg",desc:"Seduta aerea con le gambe a 90°, ruota intorno al palo mantenendo la posizione.",tip:"Piega le ginocchia esattamente a 90° e tieni le anche aperte."},
  {name:"Tuck Spin",cat:"Spin",level:"beg",desc:"Spin con gambe raccolte al petto, corpo compatto, rotazione veloce.",tip:"Più le gambe sono vicine al palo, più veloce sarà la rotazione."},
  {name:"Front Hook Spin",cat:"Spin",level:"beg",desc:"Gancio anteriore con una gamba tesa, l'altra libera e allungata verso il basso.",tip:"Attiva l'addome e mantieni la spalla bassa."},
  {name:"Ballerina Spin",cat:"Spin",level:"beg",desc:"Spin elegante con una gamba in arabesque e l'altra tesa verso il basso.",tip:"Punta sempre le dita dei piedi per un look più pulito."},
  {name:"Pencil Spin",cat:"Spin",level:"beg",desc:"Spin stretto con corpo perfettamente verticale e gambe unite.",tip:"Perfetto per lavorare sulla verticalità e sul controllo del corpo."},
  {name:"Pole Climb",cat:"Climb",level:"beg",desc:"Arrampicata base: usa i piedi a gancio alternati per salire.",tip:"Il segreto è la pressione dei piedi, non la forza delle braccia."},
  {name:"Crossed Ankle Climb",cat:"Climb",level:"beg",desc:"Salita con le caviglie incrociate che stringono il palo, gambe tese.",tip:"Usa la pressione interna delle caviglie, non le cosce."},
  {name:"Pole Sit",cat:"Static",level:"beg",desc:"Seduta sul palo tenendo con la coscia interna e la mano opposta.",tip:"La coscia deve stringere forte sopra il ginocchio."},
  {name:"Standing Pose",cat:"Static",level:"beg",desc:"Posa eretta con una mano sul palo, corpo allungato e gamba sollevata.",tip:"Punta il piede e tieni il bacino neutro."},
  {name:"Floorwork Wave",cat:"Floorwork",level:"beg",desc:"Movimento ondulatorio a terra: anca, schiena e spalle scorrono in sequenza.",tip:"Pensa a un'onda che parte dall'anca e sale su."},
  {name:"Hip Roll",cat:"Floorwork",level:"beg",desc:"Rotazione circolare delle anche in piedi o in ginocchio, fluida e continua.",tip:"Immagina di disegnare un cerchio grande con l'anca."},
  {name:"Cat Stretch",cat:"Floorwork",level:"beg",desc:"Allungamento a terra sulla schiena, aprendo il petto verso il palo.",tip:"Mantieni le spalle lontane dalle orecchie."},
  {name:"Knee Walk",cat:"Floorwork",level:"beg",desc:"Camminata in ginocchio intorno al palo con movimenti sensuali e controllati.",tip:"Usa calze per proteggere le ginocchia sul pavimento."},
  {name:"Basic Bridge",cat:"Floorwork",level:"beg",desc:"Ponte a terra con i piedi vicino al palo, apertura del petto verso l'alto.",tip:"Spingi le anche verso il soffitto, non arcare solo la schiena."},
  {name:"Pole Hold",cat:"Static",level:"beg",desc:"Tieniti al palo in piedi e porta una gamba lateralmente in arabesque bassa.",tip:"Mantieni il bacino in asse e la spalla verso il basso."},
  {name:"Side Step Spin",cat:"Spin",level:"beg",desc:"Spin laterale camminando intorno al palo con un passo e una spinta.",tip:"La spinta del piede determina la velocità della rotazione."},
  {name:"Lunge Around Pole",cat:"Floorwork",level:"beg",desc:"Affondo profondo intorno al palo con cambio di direzione fluido.",tip:"Tieni il ginocchio anteriore sopra la caviglia."},
  {name:"Pole Lean",cat:"Static",level:"beg",desc:"Inclinazione laterale con un braccio teso sul palo e il corpo diagonale.",tip:"Allunga dalla testa alla punta del piede."},
  {name:"Two-Handed Hold",cat:"Static",level:"beg",desc:"Presa con entrambe le mani sopra la testa, gambe in varie posizioni.",tip:"Buon esercizio per abituarsi al peso del corpo sulle mani."},
  {name:"Spin and Dip",cat:"Spin",level:"beg",desc:"Spin che finisce con un'inclinazione verso il basso, fluidamente.",tip:"Controlla la discesa con le braccia, non cedere di colpo."},
  {name:"Arabesque Hold",cat:"Static",level:"beg",desc:"Una gamba tesa indietro ad arabesque, mano sul palo, corpo inclinato.",tip:"Pensa a una ballerina: linea lunga dalla mano al piede."},
  {name:"Floor Spin",cat:"Floorwork",level:"beg",desc:"Rotazione a terra intorno al palo con le gambe aperte o chiuse.",tip:"Usa i calzini per scivolare facilmente sul pavimento."},
  {name:"Pole Walk",cat:"Floorwork",level:"beg",desc:"Camminata scultorea intorno al palo, con enfasi sulla postura.",tip:"Allunga il collo, porta le spalle indietro e cammina con intenzione."},
  {name:"Basic Dip",cat:"Floorwork",level:"beg",desc:"Inclinazione in avanti tenendo il palo, gambe semi-piegate.",tip:"Tieni il core attivo per proteggere la schiena bassa."},
  {name:"Single Knee Hang",cat:"Static",level:"beg",desc:"Appendi il corpo con un ginocchio gancio sul palo, corpo rilassato.",tip:"Inizia da bassa altezza e assicurati che il gancio sia stabile."},
  {name:"Attitude Spin",cat:"Spin",level:"beg",desc:"Spin con una gamba piegata in attitude e l'altra tesa verso il basso.",tip:"Punta il piede della gamba piegata e tieni l'anca aperta."},
  {name:"Pole Squat",cat:"Static",level:"beg",desc:"Squat tenendosi al palo, poi estensione verso l'alto in punta di piedi.",tip:"Ottimo per riscaldarsi e abituarsi al palo."},
  {name:"Body Wave Standing",cat:"Floorwork",level:"beg",desc:"Onda corporea in piedi vicino al palo, dal bacino alle spalle.",tip:"Inizia lentamente: ogni parte del corpo si muove in sequenza."},
  {name:"Basic Invert Prep",cat:"Static",level:"beg",desc:"Preparazione all'inversione: gambe su con aiuto del pavimento, mani sul palo.",tip:"Esercizio fondamentale per costruire la consapevolezza dell'inversione."},

  // ── INTERMEDIO ──
  {name:"Back Hook Spin",cat:"Spin",level:"int",desc:"Gancio posteriore con una gamba, il corpo ruota aprendo il fianco verso l'esterno.",tip:"Attiva il gluteo della gamba di gancio per mantenere la forma."},
  {name:"Carousel Spin",cat:"Spin",level:"int",desc:"Rotazione ampia con le gambe divaricate parallele al suolo, corpo orizzontale.",tip:"Costruisci velocità con le gambe prima di aprirle."},
  {name:"Sunwheel",cat:"Spin",level:"int",desc:"Spin con le gambe aperte in V orizzontale, corpo come una ruota che gira.",tip:"Serve buona apertura dell'anca. Scalda bene prima."},
  {name:"Straight Edge Climb",cat:"Climb",level:"int",desc:"Arrampicata senza usare i piedi, solo forza di braccia e core.",tip:"Rinforza tricipiti e dorsali prima di provarla."},
  {name:"Pencil Hold",cat:"Climb",level:"int",desc:"Tieni il corpo verticale stretto al palo con braccia e piedi incrociati.",tip:"Ottimo esercizio di forza isometrica."},
  {name:"Invert Base",cat:"Invert",level:"int",desc:"Prima inversione: gambe all'insù tenendo il palo con mani e cosce.",tip:"Impara la meccanica con l'inversione a terra prima."},
  {name:"Gemini",cat:"Invert",level:"int",desc:"Inversione con gancio della coscia esterna, corpo teso, braccio libero esteso.",tip:"Rilassa le spalle durante l'inversione, non bloccare il respiro."},
  {name:"Chopper",cat:"Invert",level:"int",desc:"Inversione senza gancio delle gambe: core e braccia reggono il corpo verticale.",tip:"Uno degli esercizi di forza più efficaci in pole."},
  {name:"Superman",cat:"Static",level:"int",desc:"Corpo orizzontale parallelo al suolo, un braccio e la coscia reggono il palo.",tip:"Il gancio della coscia deve essere sopra il ginocchio."},
  {name:"Inside Leg Hang",cat:"Invert",level:"int",desc:"Inversione con gancio della coscia interna, corpo libero verso il basso.",tip:"Testa rilassata, non tendere il collo."},
  {name:"Caterpillar",cat:"Floorwork",level:"int",desc:"Strisciamento avanzato con estensione della schiena e spinta delle braccia.",tip:"Usa calze per scivolare meglio sul pavimento."},
  {name:"Body Roll",cat:"Floorwork",level:"int",desc:"Rotazione dell'intero corpo dal basso verso l'alto contro il palo.",tip:"Ogni parte del corpo tocca il palo in sequenza: ginocchia, fianchi, petto."},
  {name:"Twisted Grip Hold",cat:"Static",level:"int",desc:"Presa con il polso ruotato verso l'esterno, base per molte figure avanzate.",tip:"Non forzare il polso. Costruisci la forza gradualmente."},
  {name:"Crossleg Spin",cat:"Spin",level:"int",desc:"Spin con le gambe incrociate, corpo compatto e rotazione controllata.",tip:"Incrocia le gambe prima di iniziare la rotazione."},
  {name:"Fan Kick Spin",cat:"Spin",level:"int",desc:"Spin con calcio aperto a ventaglio prima di avvolgere le gambe al palo.",tip:"Il calcio genera lo slancio: rendilo potente e controllato."},
  {name:"Hip Hold",cat:"Static",level:"int",desc:"Il palo è tenuto lateralmente dall'anca, corpo inclinato con un braccio libero.",tip:"Spingi l'anca contro il palo con forza costante."},
  {name:"Pole Split Stretch",cat:"Static",level:"int",desc:"Spaccata con una gamba sul palo e l'altra a terra, mani per l'equilibrio.",tip:"Ottimo stretch: tieni la posizione almeno 30 secondi."},
  {name:"Knee Hold",cat:"Static",level:"int",desc:"Il ginocchio stringe lateralmente il palo, corpo libero verso il basso o di lato.",tip:"Posiziona il palo sopra il ginocchio, non sul ginocchio."},
  {name:"Reverse Spin",cat:"Spin",level:"int",desc:"Spin eseguito nella direzione opposta alla naturale, richiede coordinazione.",tip:"Pensa prima alla mano di spinta: cambia la guida."},
  {name:"Layback",cat:"Static",level:"int",desc:"Inclinazione all'indietro tenendo il palo, corpo arcuato con testa verso il basso.",tip:"Apri il petto verso il soffitto. Non bloccare la respirazione."},
  {name:"Pole Attitude",cat:"Static",level:"int",desc:"Gamba in attitude aerea con il corpo sostenuto dal palo, posizione da balletto.",tip:"Mantieni la gamba in attitude attiva e il piede puntato."},
  {name:"Barrel Roll",cat:"Spin",level:"int",desc:"Rotazione con il corpo che si avvolge orizzontalmente intorno al palo.",tip:"Mantieni le gambe tese per una traiettoria pulita."},
  {name:"Upside Down Crucifix",cat:"Invert",level:"int",desc:"Inversione a croce: braccia aperte senza toccare il palo, coscie a gancio.",tip:"Inizia toccando il palo con le mani finché non acquisisci sicurezza."},
  {name:"Straddle Invert",cat:"Invert",level:"int",desc:"Inversione con gambe aperte in V, controllo del core per mantenerle alte.",tip:"Apri le gambe solo dopo aver raggiunto la verticale."},
  {name:"Shoulder Mount Prep",cat:"Invert",level:"int",desc:"Preparazione al shoulder mount: spinta della spalla contro il palo verso l'alto.",tip:"La spalla è il punto di appoggio principale, non le braccia."},
  {name:"Hip Flexor Stretch Pole",cat:"Floorwork",level:"int",desc:"Allungamento dell'ileopsoas con una gamba estesa indietro e il petto al palo.",tip:"Respira e rilascia tensione a ogni espirazione."},
  {name:"Back Walkover Prep",cat:"Floorwork",level:"int",desc:"Preparazione alla ruota all'indietro: ponte dinamico con spinta delle gambe.",tip:"Riscalda bene la colonna. Usa il muro per supporto inizialmente."},
  {name:"Twisted Spin",cat:"Spin",level:"int",desc:"Spin con il corpo ruotato in twisted grip, combinando forza e tecnica.",tip:"Controlla la presa twisted prima di aggiungere la rotazione."},
  {name:"Half Flag",cat:"Static",level:"int",desc:"Versione ridotta del flag: corpo semi-orizzontale con il gomito come appoggio.",tip:"Costruisci la forza laterale del core con esercizi a terra."},
  {name:"Thigh Hold",cat:"Static",level:"int",desc:"Solo la coscia tiene il palo lateralmente, corpo libero, un braccio alzato.",tip:"La coscia stringe il palo come una morsa: sopra il ginocchio."},

  // ── AVANZATO ──
  {name:"Ayesha",cat:"Static",level:"adv",desc:"Presa laterale avanzata: corpo orizzontale con solo le mani sul palo, gambe divaricate.",tip:"Costruisci prima il Twisted Grip Handstand."},
  {name:"Jade Split",cat:"Static",level:"adv",desc:"Spaccata aerea verticale con gancio della coscia interna, gambe aperte al massimo.",tip:"Fondamentale l'apertura laterale. Lavora sullo stretching ogni giorno."},
  {name:"Iron X",cat:"Static",level:"adv",desc:"Presa a croce: corpo orizzontale, solo i palmi sul palo, gambe unite e tese.",tip:"Una delle figure più difficili. Richiede anni di allenamento di forza."},
  {name:"Flag",cat:"Static",level:"adv",desc:"Corpo orizzontale perpendicolare al palo, reggendosi con una mano e un gomito.",tip:"Il gomito è l'appoggio principale: posizionalo correttamente."},
  {name:"Scorpio",cat:"Invert",level:"adv",desc:"Inversione con gancio del ginocchio, corpo arcuato, testa all'indietro.",tip:"Riscalda bene la colonna. Non forzare l'arco se la schiena è rigida."},
  {name:"Brass Monkey",cat:"Invert",level:"adv",desc:"Inversione con gancio della coscia esterna, corpo ruotato, braccio opposto allungato.",tip:"Deriva dal Gemini: prendici confidenza prima."},
  {name:"Butterfly",cat:"Invert",level:"adv",desc:"Inversione con entrambe le gambe in spaccata aerea perfettamente simmetrica.",tip:"Richiede spaccata al 100%. Lavora sulla flessibilità prima."},
  {name:"Handspring",cat:"Handspring",level:"adv",desc:"Lancio verticale sul palo con spinta delle braccia, il corpo si solleva con slancio.",tip:"Inizia da bassa altezza. La tecnica è tutto, non forzare con le braccia."},
  {name:"Deadlift Handspring",cat:"Handspring",level:"adv",desc:"Handspring eseguito lentamente senza slancio, solo con forza pura.",tip:"Richiede mesi di allenamento specifico. Non tentare senza preparazione."},
  {name:"Shoulder Mount",cat:"Invert",level:"adv",desc:"Inversione con spinta della spalla contro il palo, gambe verso l'alto senza slancio.",tip:"La spalla lavora come una leva: non è un esercizio di braccia."},
  {name:"Allegra",cat:"Invert",level:"adv",desc:"Figura a uncino con la coscia esterna e spaccata, corpo aperto e allungato.",tip:"Costruisci dalla Brass Monkey aggiungendo l'apertura delle gambe."},
  {name:"Marley",cat:"Static",level:"adv",desc:"Presa con un solo braccio e la coscia, corpo obliquo verso il basso.",tip:"Rinforza il grip con specifici esercizi di presa."},
  {name:"Cross Ankle Release",cat:"Invert",level:"adv",desc:"Inversione con caviglie incrociate che si aprono in spaccata lentamente.",tip:"Il controllo è tutto: usa i muscoli interni coscia per la discesa."},
  {name:"Twisted Grip Ayesha",cat:"Static",level:"adv",desc:"Ayesha con presa twisted: richiede enorme forza e stabilità del polso.",tip:"Non tentare senza aver consolidato sia l'Ayesha che il Twisted Grip."},
  {name:"Pole Handstand",cat:"Static",level:"adv",desc:"Verticale sul palo con entrambe le mani, corpo perfettamente allineato.",tip:"Inizia con il muro come supporto per trovare l'allineamento."},
  {name:"Janeiro",cat:"Invert",level:"adv",desc:"Inversione con una gamba in split verticale e l'altra a gancio al palo.",tip:"Richiede sia flessibilità che forza. Non affrettare i progressi."},
  {name:"Cocoon",cat:"Invert",level:"adv",desc:"Inversione con le gambe avvolte intorno al palo in posizione raccolta aerea.",tip:"Tieni le gambe strette al palo e controllate durante la discesa."},
  {name:"Dead Man",cat:"Static",level:"adv",desc:"Corpo parallelo al suolo trattenuto solo dalla coscia interna, braccia libere.",tip:"Uno dei grips più dolorosi. Rinforza la coscia interna gradualmente."},
  {name:"Remi Sit",cat:"Static",level:"adv",desc:"Seduta aerea sostenuta solo dalla coscia esterna, senza mani sul palo.",tip:"Partire dal Pole Sit e togliere le mani con fiducia progressiva."},
  {name:"Superman Split",cat:"Static",level:"adv",desc:"Variante del Superman con le gambe aperte in spaccata orizzontale.",tip:"Padroneggia il Superman base prima di aggiungere la spaccata."},
  {name:"Iguana",cat:"Invert",level:"adv",desc:"Inversione con il piede che spinge il palo dall'esterno, corpo obliquo.",tip:"Il piede è l'appoggio principale: posizionalo con precisione."},
  {name:"Python",cat:"Climb",level:"adv",desc:"Scalata avanzata avvolgendo il corpo attorno al palo con spirale continua.",tip:"Testa alta e spirale larga per un effetto visivo potente."},
  {name:"Pole Splits",cat:"Static",level:"adv",desc:"Spaccata frontale completa in aria con il palo tra le gambe come supporto.",tip:"Richiede spaccata a terra completa come prerequisito."},
  {name:"Elbow Stand",cat:"Static",level:"adv",desc:"Verticale sui gomiti con il palo tra le braccia, gambe tese verso l'alto.",tip:"Fortissimo sulla rotella. Costruiscilo con la half flag prima."},
  {name:"Flatline Scorpio",cat:"Invert",level:"adv",desc:"Scorpio con il corpo completamente orizzontale, massima estensione dell'arco.",tip:"Combinazione di flessibilità e forza del core posteriore."},
  {name:"Handspring Split",cat:"Handspring",level:"adv",desc:"Handspring con le gambe che si aprono in spaccata al momento del lancio.",tip:"Prima padroneggia handspring pulito, poi aggiungi la spaccata."},
  {name:"Ballerina Advanced",cat:"Spin",level:"adv",desc:"Spin con gamba alta in arabesque verticale e schiena arcuata, altissima flessibilità.",tip:"Serve arabesque oltre i 180°. Lavora con un trainer di flessibilità."},
  {name:"Twisted Ballerina",cat:"Spin",level:"adv",desc:"Ballerina Spin in presa twisted: combinazione tecnica estrema.",tip:"Una delle combinazioni più scenografiche e difficili. Avanzare per gradi."},
  {name:"Aerial Invert",cat:"Handspring",level:"adv",desc:"Inversione aerea senza contatto dei piedi con il suolo, puro lancio.",tip:"Non tentare senza spotter qualificato. Sicurezza prima di tutto."},
  {name:"Titanic",cat:"Static",level:"adv",desc:"Corpo in diagonale verso il basso reggendosi con un solo braccio teso, gambe aperte.",tip:"La forza della spalla è il limite: costruiscila per mesi prima."},
];

const levelLabel = {beg:"Principiante", int:"Intermedio", adv:"Avanzato"};
const levelColor = {
  beg:{bg:"#EAF3DE",text:"#3B6D11"},
  int:{bg:"#FAEEDA",text:"#854F0B"},
  adv:{bg:"#FAECE7",text:"#993C1D"},
};
const catColors = ["#EEEDFE","#E1F5EE","#FAECE7","#FBEAF0","#E6F1FB","#FAEEDA","#EAF3DE"];
const cats = ["Spin","Climb","Invert","Static","Floorwork","Handspring"];

function PoleIcon({name, cat}) {
  const pole = <line x1="50" y1="0" x2="50" y2="160" stroke="currentColor" strokeWidth="4" opacity="0.25"/>;

  const byName = {
    // ── SPIN ──
    "Fireman Spin": <svg viewBox="0 0 100 160" width="80" height="128">{pole}<circle cx="40" cy="28" r="9" fill="currentColor" opacity="0.7"/><line x1="40" y1="37" x2="44" y2="72" stroke="currentColor" strokeWidth="4" strokeLinecap="round"/><line x1="44" y1="50" x2="50" y2="38" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="42" y1="52" x2="28" y2="60" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><path d="M44 72 Q34 88 38 108 Q50 116 52 100 Q54 84 44 72" fill="none" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/></svg>,
    "Chair Spin": <svg viewBox="0 0 100 160" width="80" height="128">{pole}<circle cx="42" cy="30" r="9" fill="currentColor" opacity="0.7"/><line x1="42" y1="39" x2="44" y2="68" stroke="currentColor" strokeWidth="4" strokeLinecap="round"/><line x1="44" y1="52" x2="50" y2="40" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="42" y1="55" x2="26" y2="62" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="44" y1="68" x2="14" y2="70" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/><line x1="14" y1="70" x2="12" y2="95" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/></svg>,
    "Tuck Spin": <svg viewBox="0 0 100 160" width="80" height="128">{pole}<circle cx="42" cy="40" r="9" fill="currentColor" opacity="0.7"/><line x1="42" y1="49" x2="42" y2="70" stroke="currentColor" strokeWidth="4" strokeLinecap="round"/><line x1="42" y1="57" x2="50" y2="48" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="42" y1="57" x2="30" y2="52" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><path d="M42 70 Q26 80 26 68 Q26 56 40 56" fill="none" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/><path d="M42 70 Q58 80 56 68 Q54 56 42 56" fill="none" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/></svg>,
    "Ballerina Spin": <svg viewBox="0 0 100 160" width="80" height="128">{pole}<circle cx="42" cy="28" r="9" fill="currentColor" opacity="0.7"/><line x1="42" y1="37" x2="42" y2="76" stroke="currentColor" strokeWidth="4" strokeLinecap="round"/><line x1="42" y1="48" x2="50" y2="38" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="42" y1="50" x2="26" y2="46" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="42" y1="76" x2="40" y2="128" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/><line x1="42" y1="76" x2="82" y2="56" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/></svg>,
    "Pencil Spin": <svg viewBox="0 0 100 160" width="80" height="128">{pole}<circle cx="46" cy="18" r="9" fill="currentColor" opacity="0.7"/><line x1="46" y1="27" x2="46" y2="82" stroke="currentColor" strokeWidth="4.5" strokeLinecap="round"/><line x1="46" y1="46" x2="50" y2="38" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="46" y1="46" x2="40" y2="40" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="46" y1="82" x2="45" y2="145" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/></svg>,
    "Front Hook Spin": <svg viewBox="0 0 100 160" width="80" height="128">{pole}<circle cx="42" cy="28" r="9" fill="currentColor" opacity="0.7"/><line x1="42" y1="37" x2="44" y2="70" stroke="currentColor" strokeWidth="4" strokeLinecap="round"/><line x1="44" y1="50" x2="50" y2="40" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="42" y1="52" x2="28" y2="48" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><path d="M44 70 Q56 90 50 118" fill="none" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/><path d="M44 70 Q34 92 38 118" fill="none" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/></svg>,
    "Back Hook Spin": <svg viewBox="0 0 100 160" width="80" height="128">{pole}<circle cx="42" cy="28" r="9" fill="currentColor" opacity="0.7"/><line x1="42" y1="37" x2="44" y2="70" stroke="currentColor" strokeWidth="4" strokeLinecap="round"/><line x1="42" y1="50" x2="50" y2="40" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="42" y1="52" x2="26" y2="50" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><path d="M44 70 Q62 86 64 106" fill="none" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/><line x1="44" y1="70" x2="36" y2="118" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/></svg>,
    "Carousel Spin": <svg viewBox="0 0 100 160" width="80" height="128">{pole}<circle cx="50" cy="44" r="9" fill="currentColor" opacity="0.7"/><line x1="50" y1="53" x2="50" y2="72" stroke="currentColor" strokeWidth="4" strokeLinecap="round"/><line x1="50" y1="38" x2="24" y2="36" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="50" y1="38" x2="74" y2="36" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="50" y1="68" x2="10" y2="68" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/><line x1="50" y1="68" x2="90" y2="68" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/></svg>,
    "Sunwheel": <svg viewBox="0 0 100 160" width="80" height="128">{pole}<circle cx="50" cy="42" r="9" fill="currentColor" opacity="0.7"/><line x1="50" y1="51" x2="50" y2="70" stroke="currentColor" strokeWidth="4" strokeLinecap="round"/><line x1="50" y1="35" x2="24" y2="33" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="50" y1="35" x2="74" y2="33" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="50" y1="66" x2="6" y2="56" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/><line x1="50" y1="66" x2="94" y2="78" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/></svg>,
    "Side Step Spin": <svg viewBox="0 0 100 160" width="80" height="128">{pole}<circle cx="36" cy="32" r="9" fill="currentColor" opacity="0.7"/><line x1="36" y1="41" x2="40" y2="76" stroke="currentColor" strokeWidth="4" strokeLinecap="round"/><line x1="36" y1="52" x2="50" y2="46" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="36" y1="56" x2="22" y2="64" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="40" y1="76" x2="28" y2="122" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/><line x1="40" y1="76" x2="56" y2="120" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/></svg>,
    "Attitude Spin": <svg viewBox="0 0 100 160" width="80" height="128">{pole}<circle cx="42" cy="28" r="9" fill="currentColor" opacity="0.7"/><line x1="42" y1="37" x2="42" y2="72" stroke="currentColor" strokeWidth="4" strokeLinecap="round"/><line x1="42" y1="48" x2="50" y2="38" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="42" y1="50" x2="28" y2="48" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="42" y1="72" x2="40" y2="122" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/><path d="M42 80 Q64 76 68 60" fill="none" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/></svg>,
    "Spin and Dip": <svg viewBox="0 0 100 160" width="80" height="128">{pole}<circle cx="40" cy="55" r="9" fill="currentColor" opacity="0.7"/><line x1="40" y1="46" x2="50" y2="35" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="40" y1="64" x2="42" y2="92" stroke="currentColor" strokeWidth="4" strokeLinecap="round"/><line x1="40" y1="74" x2="24" y2="80" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="42" y1="92" x2="30" y2="135" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/><line x1="42" y1="92" x2="56" y2="132" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/></svg>,
    "Crossleg Spin": <svg viewBox="0 0 100 160" width="80" height="128">{pole}<circle cx="42" cy="32" r="9" fill="currentColor" opacity="0.7"/><line x1="42" y1="41" x2="42" y2="68" stroke="currentColor" strokeWidth="4" strokeLinecap="round"/><line x1="42" y1="52" x2="50" y2="42" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="42" y1="52" x2="30" y2="48" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><path d="M42 68 Q30 80 34 96 Q44 102 54 88 Q58 74 42 68" fill="none" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/></svg>,
    "Fan Kick Spin": <svg viewBox="0 0 100 160" width="80" height="128">{pole}<circle cx="42" cy="28" r="9" fill="currentColor" opacity="0.7"/><line x1="42" y1="37" x2="44" y2="70" stroke="currentColor" strokeWidth="4" strokeLinecap="round"/><line x1="42" y1="48" x2="50" y2="38" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="42" y1="52" x2="28" y2="50" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="42" y1="58" x2="78" y2="26" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/><line x1="44" y1="70" x2="40" y2="120" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/></svg>,
    "Reverse Spin": <svg viewBox="0 0 100 160" width="80" height="128">{pole}<circle cx="58" cy="28" r="9" fill="currentColor" opacity="0.7"/><line x1="58" y1="37" x2="54" y2="72" stroke="currentColor" strokeWidth="4" strokeLinecap="round"/><line x1="58" y1="48" x2="50" y2="38" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="58" y1="52" x2="72" y2="50" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="54" y1="72" x2="44" y2="120" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/><line x1="54" y1="72" x2="66" y2="118" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/></svg>,
    "Twisted Spin": <svg viewBox="0 0 100 160" width="80" height="128">{pole}<circle cx="42" cy="30" r="9" fill="currentColor" opacity="0.7"/><line x1="42" y1="39" x2="50" y2="30" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="42" y1="39" x2="44" y2="74" stroke="currentColor" strokeWidth="4" strokeLinecap="round"/><line x1="44" y1="55" x2="28" y2="52" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="44" y1="74" x2="36" y2="122" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/><line x1="44" y1="74" x2="58" y2="120" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/></svg>,
    "Barrel Roll": <svg viewBox="0 0 100 160" width="80" height="128">{pole}<circle cx="50" cy="50" r="9" fill="currentColor" opacity="0.7"/><line x1="50" y1="41" x2="50" y2="30" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="50" y1="59" x2="50" y2="80" stroke="currentColor" strokeWidth="4" strokeLinecap="round"/><line x1="50" y1="70" x2="14" y2="70" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/><line x1="50" y1="70" x2="86" y2="70" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/></svg>,
    "Ballerina Advanced": <svg viewBox="0 0 100 160" width="80" height="128">{pole}<circle cx="42" cy="26" r="9" fill="currentColor" opacity="0.7"/><line x1="42" y1="35" x2="50" y2="26" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="42" y1="35" x2="42" y2="72" stroke="currentColor" strokeWidth="4" strokeLinecap="round"/><line x1="42" y1="50" x2="24" y2="56" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="42" y1="72" x2="40" y2="128" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/><line x1="42" y1="72" x2="86" y2="38" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/></svg>,
    "Twisted Ballerina": <svg viewBox="0 0 100 160" width="80" height="128">{pole}<circle cx="42" cy="26" r="9" fill="currentColor" opacity="0.7"/><line x1="42" y1="35" x2="50" y2="26" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="42" y1="35" x2="42" y2="72" stroke="currentColor" strokeWidth="4" strokeLinecap="round"/><line x1="42" y1="52" x2="26" y2="52" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="42" y1="72" x2="40" y2="126" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/><line x1="42" y1="72" x2="84" y2="44" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/></svg>,

    // ── CLIMB ──
    "Pole Climb": <svg viewBox="0 0 100 160" width="80" height="128">{pole}<circle cx="44" cy="16" r="9" fill="currentColor" opacity="0.7"/><line x1="44" y1="25" x2="46" y2="62" stroke="currentColor" strokeWidth="4" strokeLinecap="round"/><line x1="44" y1="36" x2="50" y2="26" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="44" y1="42" x2="32" y2="52" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="46" y1="62" x2="40" y2="98" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/><line x1="46" y1="62" x2="56" y2="98" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/><line x1="40" y1="98" x2="50" y2="106" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="56" y1="98" x2="50" y2="106" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/></svg>,
    "Crossed Ankle Climb": <svg viewBox="0 0 100 160" width="80" height="128">{pole}<circle cx="44" cy="18" r="9" fill="currentColor" opacity="0.7"/><line x1="44" y1="27" x2="46" y2="64" stroke="currentColor" strokeWidth="4" strokeLinecap="round"/><line x1="44" y1="37" x2="50" y2="28" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="44" y1="42" x2="30" y2="52" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="46" y1="64" x2="42" y2="112" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/><line x1="46" y1="64" x2="56" y2="110" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/><line x1="42" y1="112" x2="56" y2="110" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/></svg>,
    "Straight Edge Climb": <svg viewBox="0 0 100 160" width="80" height="128">{pole}<circle cx="46" cy="15" r="9" fill="currentColor" opacity="0.7"/><line x1="46" y1="24" x2="46" y2="66" stroke="currentColor" strokeWidth="4.5" strokeLinecap="round"/><line x1="46" y1="36" x2="50" y2="26" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="46" y1="40" x2="50" y2="52" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="46" y1="66" x2="44" y2="118" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/><line x1="46" y1="66" x2="50" y2="120" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/></svg>,
    "Pencil Hold": <svg viewBox="0 0 100 160" width="80" height="128">{pole}<circle cx="46" cy="17" r="9" fill="currentColor" opacity="0.7"/><line x1="46" y1="26" x2="46" y2="68" stroke="currentColor" strokeWidth="4.5" strokeLinecap="round"/><line x1="46" y1="38" x2="50" y2="28" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="46" y1="42" x2="50" y2="54" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="46" y1="68" x2="46" y2="132" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/></svg>,
    "Python": <svg viewBox="0 0 100 160" width="80" height="128">{pole}<circle cx="44" cy="20" r="9" fill="currentColor" opacity="0.7"/><path d="M44 29 Q28 45 44 62 Q60 78 44 92" fill="none" stroke="currentColor" strokeWidth="4" strokeLinecap="round"/><line x1="44" y1="38" x2="50" y2="28" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="44" y1="44" x2="30" y2="52" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="44" y1="92" x2="38" y2="132" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/><line x1="44" y1="92" x2="54" y2="130" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/></svg>,

    // ── INVERT ──
    "Invert Base": <svg viewBox="0 0 100 160" width="80" height="128">{pole}<circle cx="46" cy="132" r="9" fill="currentColor" opacity="0.7"/><line x1="46" y1="123" x2="46" y2="82" stroke="currentColor" strokeWidth="4" strokeLinecap="round"/><line x1="46" y1="102" x2="34" y2="92" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="46" y1="102" x2="58" y2="92" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="46" y1="82" x2="30" y2="44" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/><line x1="46" y1="82" x2="62" y2="44" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/></svg>,
    "Gemini": <svg viewBox="0 0 100 160" width="80" height="128">{pole}<circle cx="44" cy="128" r="9" fill="currentColor" opacity="0.7"/><line x1="44" y1="119" x2="46" y2="82" stroke="currentColor" strokeWidth="4" strokeLinecap="round"/><line x1="46" y1="100" x2="32" y2="92" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="46" y1="100" x2="60" y2="94" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="46" y1="82" x2="24" y2="40" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/><line x1="46" y1="82" x2="72" y2="52" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/></svg>,
    "Inside Leg Hang": <svg viewBox="0 0 100 160" width="80" height="128">{pole}<circle cx="46" cy="130" r="9" fill="currentColor" opacity="0.7"/><line x1="46" y1="121" x2="46" y2="84" stroke="currentColor" strokeWidth="4" strokeLinecap="round"/><line x1="46" y1="102" x2="32" y2="94" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="46" y1="102" x2="58" y2="94" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="46" y1="84" x2="34" y2="42" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/><line x1="46" y1="84" x2="58" y2="42" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/></svg>,
    "Chopper": <svg viewBox="0 0 100 160" width="80" height="128">{pole}<circle cx="46" cy="132" r="9" fill="currentColor" opacity="0.7"/><line x1="46" y1="123" x2="46" y2="78" stroke="currentColor" strokeWidth="4" strokeLinecap="round"/><line x1="46" y1="96" x2="28" y2="88" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="46" y1="96" x2="64" y2="88" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="46" y1="78" x2="44" y2="28" stroke="currentColor" strokeWidth="4.5" strokeLinecap="round"/></svg>,
    "Scorpio": <svg viewBox="0 0 100 160" width="80" height="128">{pole}<circle cx="44" cy="130" r="9" fill="currentColor" opacity="0.7"/><line x1="44" y1="121" x2="46" y2="84" stroke="currentColor" strokeWidth="4" strokeLinecap="round"/><line x1="46" y1="100" x2="32" y2="92" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="46" y1="100" x2="60" y2="94" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><path d="M46 84 Q28 58 16 36" fill="none" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/><path d="M46 84 Q66 56 74 36" fill="none" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/></svg>,
    "Brass Monkey": <svg viewBox="0 0 100 160" width="80" height="128">{pole}<circle cx="42" cy="125" r="9" fill="currentColor" opacity="0.7"/><line x1="42" y1="116" x2="46" y2="80" stroke="currentColor" strokeWidth="4" strokeLinecap="round"/><line x1="46" y1="98" x2="62" y2="90" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="46" y1="98" x2="30" y2="90" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="46" y1="80" x2="18" y2="40" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/><line x1="46" y1="80" x2="76" y2="55" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/></svg>,
    "Butterfly": <svg viewBox="0 0 100 160" width="80" height="128">{pole}<circle cx="50" cy="130" r="9" fill="currentColor" opacity="0.7"/><line x1="50" y1="121" x2="50" y2="84" stroke="currentColor" strokeWidth="4" strokeLinecap="round"/><line x1="50" y1="100" x2="36" y2="92" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="50" y1="100" x2="64" y2="92" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="50" y1="84" x2="8" y2="84" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/><line x1="50" y1="84" x2="92" y2="84" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/></svg>,
    "Straddle Invert": <svg viewBox="0 0 100 160" width="80" height="128">{pole}<circle cx="46" cy="130" r="9" fill="currentColor" opacity="0.7"/><line x1="46" y1="121" x2="46" y2="84" stroke="currentColor" strokeWidth="4" strokeLinecap="round"/><line x1="46" y1="102" x2="32" y2="94" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="46" y1="102" x2="60" y2="94" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="46" y1="84" x2="14" y2="54" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/><line x1="46" y1="84" x2="78" y2="54" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/></svg>,
    "Upside Down Crucifix": <svg viewBox="0 0 100 160" width="80" height="128">{pole}<circle cx="50" cy="132" r="9" fill="currentColor" opacity="0.7"/><line x1="50" y1="123" x2="50" y2="84" stroke="currentColor" strokeWidth="4" strokeLinecap="round"/><line x1="50" y1="100" x2="14" y2="100" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="50" y1="100" x2="86" y2="100" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="50" y1="84" x2="44" y2="34" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/><line x1="50" y1="84" x2="56" y2="34" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/></svg>,
    "Shoulder Mount": <svg viewBox="0 0 100 160" width="80" height="128">{pole}<circle cx="46" cy="132" r="9" fill="currentColor" opacity="0.7"/><line x1="46" y1="123" x2="46" y2="88" stroke="currentColor" strokeWidth="4" strokeLinecap="round"/><line x1="46" y1="104" x2="50" y2="92" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="46" y1="104" x2="36" y2="94" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="46" y1="88" x2="44" y2="20" stroke="currentColor" strokeWidth="4.5" strokeLinecap="round"/></svg>,
    "Allegra": <svg viewBox="0 0 100 160" width="80" height="128">{pole}<circle cx="44" cy="126" r="9" fill="currentColor" opacity="0.7"/><line x1="44" y1="117" x2="46" y2="82" stroke="currentColor" strokeWidth="4" strokeLinecap="round"/><line x1="46" y1="98" x2="62" y2="92" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="46" y1="98" x2="28" y2="90" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="46" y1="82" x2="10" y2="58" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/><line x1="46" y1="82" x2="86" y2="60" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/></svg>,
    "Cross Ankle Release": <svg viewBox="0 0 100 160" width="80" height="128">{pole}<circle cx="50" cy="130" r="9" fill="currentColor" opacity="0.7"/><line x1="50" y1="121" x2="50" y2="84" stroke="currentColor" strokeWidth="4" strokeLinecap="round"/><line x1="50" y1="102" x2="34" y2="94" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="50" y1="102" x2="66" y2="94" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="50" y1="84" x2="12" y2="46" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/><line x1="50" y1="84" x2="88" y2="46" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/></svg>,
    "Janeiro": <svg viewBox="0 0 100 160" width="80" height="128">{pole}<circle cx="44" cy="126" r="9" fill="currentColor" opacity="0.7"/><line x1="44" y1="117" x2="46" y2="84" stroke="currentColor" strokeWidth="4" strokeLinecap="round"/><line x1="46" y1="100" x2="60" y2="92" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="46" y1="100" x2="30" y2="90" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="46" y1="84" x2="46" y2="14" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/><line x1="46" y1="84" x2="86" y2="68" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/></svg>,
    "Cocoon": <svg viewBox="0 0 100 160" width="80" height="128">{pole}<circle cx="46" cy="126" r="9" fill="currentColor" opacity="0.7"/><line x1="46" y1="117" x2="46" y2="88" stroke="currentColor" strokeWidth="4" strokeLinecap="round"/><line x1="46" y1="102" x2="34" y2="94" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="46" y1="102" x2="58" y2="94" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><path d="M46 88 Q30 70 32 52 Q34 38 46 38 Q58 38 60 52 Q62 70 46 88" fill="none" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/></svg>,
    "Iguana": <svg viewBox="0 0 100 160" width="80" height="128">{pole}<circle cx="40" cy="126" r="9" fill="currentColor" opacity="0.7"/><line x1="40" y1="117" x2="44" y2="82" stroke="currentColor" strokeWidth="4" strokeLinecap="round"/><line x1="44" y1="98" x2="58" y2="90" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="44" y1="98" x2="28" y2="90" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="44" y1="82" x2="16" y2="46" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/><line x1="44" y1="82" x2="70" y2="64" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/><line x1="70" y1="64" x2="74" y2="50" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round"/></svg>,
    "Flatline Scorpio": <svg viewBox="0 0 100 160" width="80" height="128">{pole}<circle cx="44" cy="80" r="9" fill="currentColor" opacity="0.7"/><line x1="44" y1="71" x2="46" y2="52" stroke="currentColor" strokeWidth="4" strokeLinecap="round"/><line x1="44" y1="89" x2="46" y2="110" stroke="currentColor" strokeWidth="4" strokeLinecap="round"/><line x1="44" y1="78" x2="24" y2="70" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="44" y1="84" x2="62" y2="80" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="46" y1="52" x2="6" y2="52" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/><line x1="46" y1="110" x2="84" y2="110" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/></svg>,

    // ── STATIC ──
    "Pole Sit": <svg viewBox="0 0 100 160" width="80" height="128">{pole}<circle cx="44" cy="42" r="9" fill="currentColor" opacity="0.7"/><line x1="44" y1="51" x2="44" y2="78" stroke="currentColor" strokeWidth="4" strokeLinecap="round"/><line x1="44" y1="62" x2="50" y2="52" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="44" y1="62" x2="32" y2="58" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="44" y1="78" x2="16" y2="80" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/><line x1="16" y1="80" x2="12" y2="108" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/><line x1="44" y1="78" x2="50" y2="118" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/></svg>,
    "Standing Pose": <svg viewBox="0 0 100 160" width="80" height="128">{pole}<circle cx="44" cy="22" r="9" fill="currentColor" opacity="0.7"/><line x1="44" y1="31" x2="44" y2="74" stroke="currentColor" strokeWidth="4" strokeLinecap="round"/><line x1="44" y1="44" x2="50" y2="34" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="44" y1="48" x2="28" y2="56" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="44" y1="74" x2="42" y2="132" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/><line x1="44" y1="74" x2="70" y2="60" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/></svg>,
    "Superman": <svg viewBox="0 0 100 160" width="80" height="128">{pole}<circle cx="46" cy="68" r="9" fill="currentColor" opacity="0.7"/><line x1="46" y1="59" x2="50" y2="48" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="46" y1="77" x2="46" y2="92" stroke="currentColor" strokeWidth="4" strokeLinecap="round"/><line x1="46" y1="82" x2="10" y2="82" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/><line x1="46" y1="82" x2="86" y2="82" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/><line x1="46" y1="68" x2="24" y2="62" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/></svg>,
    "Ayesha": <svg viewBox="0 0 100 160" width="80" height="128">{pole}<circle cx="46" cy="75" r="9" fill="currentColor" opacity="0.7"/><line x1="46" y1="66" x2="50" y2="52" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="46" y1="70" x2="50" y2="84" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="46" y1="75" x2="6" y2="75" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/><line x1="46" y1="75" x2="90" y2="75" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/></svg>,
    "Jade Split": <svg viewBox="0 0 100 160" width="80" height="128">{pole}<circle cx="46" cy="112" r="9" fill="currentColor" opacity="0.7"/><line x1="46" y1="103" x2="46" y2="72" stroke="currentColor" strokeWidth="4" strokeLinecap="round"/><line x1="46" y1="88" x2="60" y2="82" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="46" y1="88" x2="28" y2="82" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="46" y1="72" x2="46" y2="14" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/><line x1="46" y1="72" x2="92" y2="72" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/></svg>,
    "Iron X": <svg viewBox="0 0 100 160" width="80" height="128">{pole}<circle cx="46" cy="74" r="9" fill="currentColor" opacity="0.7"/><line x1="46" y1="65" x2="50" y2="50" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="46" y1="68" x2="50" y2="84" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="46" y1="74" x2="4" y2="64" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/><line x1="46" y1="74" x2="92" y2="84" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/></svg>,
    "Flag": <svg viewBox="0 0 100 160" width="80" height="128">{pole}<circle cx="46" cy="72" r="9" fill="currentColor" opacity="0.7"/><line x1="46" y1="63" x2="50" y2="50" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="46" y1="72" x2="50" y2="88" stroke="currentColor" strokeWidth="4" strokeLinecap="round"/><line x1="46" y1="72" x2="4" y2="72" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/><line x1="46" y1="72" x2="90" y2="72" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/></svg>,
    "Twisted Grip Hold": <svg viewBox="0 0 100 160" width="80" height="128">{pole}<circle cx="44" cy="30" r="9" fill="currentColor" opacity="0.7"/><line x1="44" y1="39" x2="50" y2="28" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="44" y1="39" x2="44" y2="76" stroke="currentColor" strokeWidth="4" strokeLinecap="round"/><line x1="44" y1="56" x2="28" y2="52" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="44" y1="76" x2="38" y2="132" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/><line x1="44" y1="76" x2="54" y2="130" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/></svg>,
    "Hip Hold": <svg viewBox="0 0 100 160" width="80" height="128">{pole}<circle cx="42" cy="38" r="9" fill="currentColor" opacity="0.7"/><line x1="42" y1="47" x2="44" y2="80" stroke="currentColor" strokeWidth="4" strokeLinecap="round"/><line x1="42" y1="58" x2="50" y2="48" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="42" y1="60" x2="18" y2="52" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="44" y1="80" x2="34" y2="132" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/><line x1="44" y1="80" x2="58" y2="130" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/></svg>,
    "Pole Split Stretch": <svg viewBox="0 0 100 160" width="80" height="128">{pole}<circle cx="46" cy="55" r="9" fill="currentColor" opacity="0.7"/><line x1="46" y1="46" x2="50" y2="34" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="46" y1="64" x2="46" y2="88" stroke="currentColor" strokeWidth="4" strokeLinecap="round"/><line x1="46" y1="78" x2="12" y2="78" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/><line x1="46" y1="78" x2="80" y2="78" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/><line x1="46" y1="88" x2="44" y2="138" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/></svg>,
    "Knee Hold": <svg viewBox="0 0 100 160" width="80" height="128">{pole}<circle cx="44" cy="46" r="9" fill="currentColor" opacity="0.7"/><line x1="44" y1="37" x2="50" y2="26" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="44" y1="55" x2="44" y2="80" stroke="currentColor" strokeWidth="4" strokeLinecap="round"/><line x1="44" y1="68" x2="24" y2="62" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="44" y1="80" x2="18" y2="98" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/><line x1="44" y1="80" x2="58" y2="122" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/></svg>,
    "Layback": <svg viewBox="0 0 100 160" width="80" height="128">{pole}<circle cx="44" cy="34" r="9" fill="currentColor" opacity="0.7"/><path d="M44 43 Q50 64 58 80 Q64 94 60 110" fill="none" stroke="currentColor" strokeWidth="4" strokeLinecap="round"/><line x1="44" y1="55" x2="50" y2="45" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="50" y1="64" x2="32" y2="70" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="60" y1="110" x2="44" y2="136" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/><line x1="60" y1="110" x2="72" y2="132" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/></svg>,
    "Pole Attitude": <svg viewBox="0 0 100 160" width="80" height="128">{pole}<circle cx="44" cy="24" r="9" fill="currentColor" opacity="0.7"/><line x1="44" y1="33" x2="44" y2="70" stroke="currentColor" strokeWidth="4" strokeLinecap="round"/><line x1="44" y1="46" x2="50" y2="36" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="44" y1="50" x2="26" y2="56" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="44" y1="70" x2="42" y2="124" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/><path d="M44 78 Q68 72 72 56" fill="none" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/></svg>,
    "Half Flag": <svg viewBox="0 0 100 160" width="80" height="128">{pole}<circle cx="44" cy="68" r="9" fill="currentColor" opacity="0.7"/><line x1="44" y1="59" x2="50" y2="46" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="44" y1="77" x2="44" y2="94" stroke="currentColor" strokeWidth="4" strokeLinecap="round"/><line x1="44" y1="82" x2="10" y2="86" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/><line x1="44" y1="82" x2="82" y2="80" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/></svg>,
    "Thigh Hold": <svg viewBox="0 0 100 160" width="80" height="128">{pole}<circle cx="44" cy="36" r="9" fill="currentColor" opacity="0.7"/><line x1="44" y1="45" x2="44" y2="78" stroke="currentColor" strokeWidth="4" strokeLinecap="round"/><line x1="44" y1="55" x2="50" y2="44" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="44" y1="55" x2="18" y2="28" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="44" y1="78" x2="36" y2="132" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/><line x1="44" y1="78" x2="56" y2="130" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/></svg>,
    "Marley": <svg viewBox="0 0 100 160" width="80" height="128">{pole}<circle cx="46" cy="54" r="9" fill="currentColor" opacity="0.7"/><line x1="46" y1="45" x2="50" y2="30" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="46" y1="63" x2="48" y2="90" stroke="currentColor" strokeWidth="4" strokeLinecap="round"/><line x1="46" y1="74" x2="12" y2="82" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/><line x1="48" y1="90" x2="34" y2="132" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/><line x1="48" y1="90" x2="62" y2="130" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/></svg>,
    "Twisted Grip Ayesha": <svg viewBox="0 0 100 160" width="80" height="128">{pole}<circle cx="46" cy="74" r="9" fill="currentColor" opacity="0.7"/><line x1="46" y1="65" x2="50" y2="50" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="46" y1="69" x2="50" y2="84" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="46" y1="74" x2="4" y2="66" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/><line x1="46" y1="74" x2="92" y2="80" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/></svg>,
    "Pole Handstand": <svg viewBox="0 0 100 160" width="80" height="128">{pole}<circle cx="46" cy="132" r="9" fill="currentColor" opacity="0.7"/><line x1="46" y1="123" x2="46" y2="80" stroke="currentColor" strokeWidth="4" strokeLinecap="round"/><line x1="46" y1="102" x2="50" y2="90" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="46" y1="102" x2="40" y2="90" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="46" y1="80" x2="44" y2="14" stroke="currentColor" strokeWidth="4.5" strokeLinecap="round"/></svg>,
    "Dead Man": <svg viewBox="0 0 100 160" width="80" height="128">{pole}<circle cx="46" cy="80" r="9" fill="currentColor" opacity="0.7"/><line x1="46" y1="71" x2="18" y2="55" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="46" y1="71" x2="74" y2="55" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="46" y1="89" x2="46" y2="100" stroke="currentColor" strokeWidth="4" strokeLinecap="round"/><line x1="46" y1="96" x2="10" y2="96" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/><line x1="46" y1="96" x2="84" y2="96" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/></svg>,
    "Remi Sit": <svg viewBox="0 0 100 160" width="80" height="128">{pole}<circle cx="44" cy="48" r="9" fill="currentColor" opacity="0.7"/><line x1="44" y1="39" x2="18" y2="28" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="44" y1="57" x2="44" y2="82" stroke="currentColor" strokeWidth="4" strokeLinecap="round"/><line x1="44" y1="70" x2="14" y2="72" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/><line x1="14" y1="72" x2="10" y2="92" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/><line x1="44" y1="82" x2="50" y2="132" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/></svg>,
    "Superman Split": <svg viewBox="0 0 100 160" width="80" height="128">{pole}<circle cx="46" cy="70" r="9" fill="currentColor" opacity="0.7"/><line x1="46" y1="61" x2="50" y2="48" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="46" y1="79" x2="46" y2="94" stroke="currentColor" strokeWidth="4" strokeLinecap="round"/><line x1="46" y1="84" x2="6" y2="68" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/><line x1="46" y1="84" x2="90" y2="100" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/><line x1="46" y1="70" x2="20" y2="65" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/></svg>,
    "Elbow Stand": <svg viewBox="0 0 100 160" width="80" height="128">{pole}<circle cx="46" cy="132" r="9" fill="currentColor" opacity="0.7"/><line x1="46" y1="123" x2="44" y2="90" stroke="currentColor" strokeWidth="4" strokeLinecap="round"/><line x1="44" y1="106" x2="28" y2="102" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="44" y1="106" x2="60" y2="102" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="44" y1="90" x2="44" y2="18" stroke="currentColor" strokeWidth="4.5" strokeLinecap="round"/></svg>,
    "Pole Splits": <svg viewBox="0 0 100 160" width="80" height="128">{pole}<circle cx="46" cy="108" r="9" fill="currentColor" opacity="0.7"/><line x1="46" y1="99" x2="46" y2="72" stroke="currentColor" strokeWidth="4" strokeLinecap="round"/><line x1="46" y1="85" x2="32" y2="80" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="46" y1="85" x2="62" y2="80" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="46" y1="72" x2="6" y2="72" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/><line x1="46" y1="72" x2="88" y2="72" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/></svg>,
    "Titanic": <svg viewBox="0 0 100 160" width="80" height="128">{pole}<circle cx="46" cy="62" r="9" fill="currentColor" opacity="0.7"/><line x1="46" y1="53" x2="50" y2="38" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="46" y1="71" x2="46" y2="94" stroke="currentColor" strokeWidth="4" strokeLinecap="round"/><line x1="46" y1="82" x2="6" y2="96" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/><line x1="46" y1="82" x2="86" y2="70" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/></svg>,
    "Pole Lean": <svg viewBox="0 0 100 160" width="80" height="128">{pole}<circle cx="40" cy="28" r="9" fill="currentColor" opacity="0.7"/><line x1="40" y1="37" x2="36" y2="78" stroke="currentColor" strokeWidth="4" strokeLinecap="round"/><line x1="40" y1="48" x2="50" y2="38" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="40" y1="52" x2="24" y2="62" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="36" y1="78" x2="28" y2="132" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/><line x1="36" y1="78" x2="48" y2="130" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/></svg>,
    "Two-Handed Hold": <svg viewBox="0 0 100 160" width="80" height="128">{pole}<circle cx="46" cy="24" r="9" fill="currentColor" opacity="0.7"/><line x1="46" y1="33" x2="46" y2="70" stroke="currentColor" strokeWidth="4" strokeLinecap="round"/><line x1="46" y1="44" x2="50" y2="30" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="46" y1="44" x2="50" y2="54" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="46" y1="70" x2="38" y2="132" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/><line x1="46" y1="70" x2="56" y2="130" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/></svg>,
    "Arabesque Hold": <svg viewBox="0 0 100 160" width="80" height="128">{pole}<circle cx="44" cy="26" r="9" fill="currentColor" opacity="0.7"/><line x1="44" y1="35" x2="44" y2="70" stroke="currentColor" strokeWidth="4" strokeLinecap="round"/><line x1="44" y1="46" x2="50" y2="36" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="44" y1="50" x2="28" y2="58" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="44" y1="70" x2="42" y2="128" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/><line x1="44" y1="75" x2="84" y2="58" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/></svg>,
    "Single Knee Hang": <svg viewBox="0 0 100 160" width="80" height="128">{pole}<circle cx="46" cy="116" r="9" fill="currentColor" opacity="0.7"/><line x1="46" y1="107" x2="46" y2="72" stroke="currentColor" strokeWidth="4" strokeLinecap="round"/><line x1="46" y1="90" x2="32" y2="82" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="46" y1="90" x2="60" y2="82" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="46" y1="72" x2="30" y2="38" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/><line x1="46" y1="72" x2="52" y2="26" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/></svg>,
    "Pole Hold": <svg viewBox="0 0 100 160" width="80" height="128">{pole}<circle cx="44" cy="24" r="9" fill="currentColor" opacity="0.7"/><line x1="44" y1="33" x2="44" y2="74" stroke="currentColor" strokeWidth="4" strokeLinecap="round"/><line x1="44" y1="44" x2="50" y2="34" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="44" y1="50" x2="26" y2="58" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="44" y1="74" x2="42" y2="132" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/><line x1="44" y1="84" x2="78" y2="84" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/></svg>,

    // ── FLOORWORK ──
    "Floorwork Wave": <svg viewBox="0 0 100 160" width="80" height="128">{pole}<circle cx="44" cy="58" r="9" fill="currentColor" opacity="0.7"/><path d="M44 67 Q40 82 44 98 Q48 110 44 126" fill="none" stroke="currentColor" strokeWidth="4" strokeLinecap="round"/><line x1="44" y1="80" x2="26" y2="78" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="44" y1="86" x2="64" y2="88" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="44" y1="126" x2="12" y2="130" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/><line x1="44" y1="126" x2="76" y2="128" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/></svg>,
    "Hip Roll": <svg viewBox="0 0 100 160" width="80" height="128">{pole}<circle cx="44" cy="34" r="9" fill="currentColor" opacity="0.7"/><line x1="44" y1="43" x2="44" y2="76" stroke="currentColor" strokeWidth="4" strokeLinecap="round"/><line x1="44" y1="54" x2="50" y2="44" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="44" y1="58" x2="28" y2="56" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><path d="M44 76 Q58 84 60 96 Q58 110 44 110" fill="none" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/><line x1="44" y1="110" x2="36" y2="150" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/><line x1="44" y1="110" x2="56" y2="150" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/></svg>,
    "Cat Stretch": <svg viewBox="0 0 100 160" width="80" height="128">{pole}<circle cx="44" cy="110" r="9" fill="currentColor" opacity="0.7"/><path d="M44 101 Q42 84 46 68 Q50 52 44 40" fill="none" stroke="currentColor" strokeWidth="4" strokeLinecap="round"/><line x1="44" y1="84" x2="22" y2="88" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="44" y1="88" x2="66" y2="82" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="44" y1="119" x2="14" y2="132" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/><line x1="44" y1="119" x2="74" y2="130" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/></svg>,
    "Knee Walk": <svg viewBox="0 0 100 160" width="80" height="128">{pole}<circle cx="44" cy="40" r="9" fill="currentColor" opacity="0.7"/><line x1="44" y1="49" x2="44" y2="80" stroke="currentColor" strokeWidth="4" strokeLinecap="round"/><line x1="44" y1="60" x2="50" y2="50" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="44" y1="64" x2="30" y2="60" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="44" y1="80" x2="24" y2="114" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/><line x1="44" y1="80" x2="58" y2="116" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/><line x1="24" y1="114" x2="22" y2="130" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round"/><line x1="58" y1="116" x2="60" y2="130" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round"/></svg>,
    "Basic Bridge": <svg viewBox="0 0 100 160" width="80" height="128">{pole}<circle cx="46" cy="108" r="9" fill="currentColor" opacity="0.7"/><path d="M46 99 Q44 82 46 66 Q50 48 46 34" fill="none" stroke="currentColor" strokeWidth="4" strokeLinecap="round"/><line x1="46" y1="78" x2="26" y2="72" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="46" y1="78" x2="66" y2="74" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="46" y1="117" x2="18" y2="142" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/><line x1="46" y1="117" x2="72" y2="142" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/></svg>,
    "Lunge Around Pole": <svg viewBox="0 0 100 160" width="80" height="128">{pole}<circle cx="42" cy="30" r="9" fill="currentColor" opacity="0.7"/><line x1="42" y1="39" x2="44" y2="74" stroke="currentColor" strokeWidth="4" strokeLinecap="round"/><line x1="42" y1="50" x2="50" y2="40" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="42" y1="54" x2="26" y2="52" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="44" y1="74" x2="18" y2="118" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/><line x1="44" y1="74" x2="70" y2="105" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/><line x1="70" y1="105" x2="76" y2="138" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/></svg>,
    "Body Roll": <svg viewBox="0 0 100 160" width="80" height="128">{pole}<circle cx="44" cy="34" r="9" fill="currentColor" opacity="0.7"/><path d="M44 43 Q50 64 46 84 Q42 100 50 120" fill="none" stroke="currentColor" strokeWidth="4" strokeLinecap="round"/><line x1="44" y1="60" x2="28" y2="58" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="46" y1="76" x2="64" y2="72" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="50" y1="120" x2="34" y2="148" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/><line x1="50" y1="120" x2="64" y2="146" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/></svg>,
    "Caterpillar": <svg viewBox="0 0 100 160" width="80" height="128">{pole}<circle cx="44" cy="88" r="9" fill="currentColor" opacity="0.7"/><path d="M44 79 Q42 62 44 48 Q48 34 44 22" fill="none" stroke="currentColor" strokeWidth="4" strokeLinecap="round"/><line x1="44" y1="62" x2="24" y2="58" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="44" y1="62" x2="66" y2="56" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="44" y1="97" x2="14" y2="116" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/><line x1="44" y1="97" x2="72" y2="120" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/></svg>,
    "Hip Flexor Stretch Pole": <svg viewBox="0 0 100 160" width="80" height="128">{pole}<circle cx="44" cy="42" r="9" fill="currentColor" opacity="0.7"/><line x1="44" y1="51" x2="44" y2="80" stroke="currentColor" strokeWidth="4" strokeLinecap="round"/><line x1="44" y1="62" x2="50" y2="52" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="44" y1="64" x2="28" y2="60" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="44" y1="80" x2="22" y2="118" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/><line x1="44" y1="80" x2="72" y2="132" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/><line x1="22" y1="118" x2="16" y2="138" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round"/></svg>,
    "Back Walkover Prep": <svg viewBox="0 0 100 160" width="80" height="128">{pole}<circle cx="44" cy="98" r="9" fill="currentColor" opacity="0.7"/><path d="M44 89 Q42 72 46 56 Q50 40 44 28" fill="none" stroke="currentColor" strokeWidth="4" strokeLinecap="round"/><line x1="44" y1="72" x2="24" y2="68" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="44" y1="72" x2="66" y2="66" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="44" y1="28" x2="28" y2="12" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/><line x1="44" y1="107" x2="16" y2="136" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/><line x1="44" y1="107" x2="68" y2="138" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/></svg>,
    "Basic Dip": <svg viewBox="0 0 100 160" width="80" height="128">{pole}<circle cx="42" cy="48" r="9" fill="currentColor" opacity="0.7"/><line x1="42" y1="39" x2="50" y2="28" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="42" y1="57" x2="44" y2="84" stroke="currentColor" strokeWidth="4" strokeLinecap="round"/><line x1="42" y1="68" x2="24" y2="72" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="44" y1="84" x2="28" y2="128" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/><line x1="44" y1="84" x2="60" y2="126" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/></svg>,
    "Body Wave Standing": <svg viewBox="0 0 100 160" width="80" height="128">{pole}<circle cx="44" cy="28" r="9" fill="currentColor" opacity="0.7"/><path d="M44 37 Q50 56 44 74 Q38 90 44 108" fill="none" stroke="currentColor" strokeWidth="4" strokeLinecap="round"/><line x1="44" y1="54" x2="28" y2="52" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="44" y1="70" x2="62" y2="68" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="44" y1="108" x2="36" y2="150" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/><line x1="44" y1="108" x2="54" y2="150" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/></svg>,
    "Floor Spin": <svg viewBox="0 0 100 160" width="80" height="128">{pole}<circle cx="44" cy="88" r="9" fill="currentColor" opacity="0.7"/><line x1="44" y1="79" x2="50" y2="64" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="44" y1="81" x2="28" y2="68" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="44" y1="97" x2="44" y2="116" stroke="currentColor" strokeWidth="4" strokeLinecap="round"/><line x1="44" y1="108" x2="8" y2="116" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/><line x1="44" y1="108" x2="82" y2="108" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/></svg>,
    "Pole Walk": <svg viewBox="0 0 100 160" width="80" height="128">{pole}<circle cx="44" cy="24" r="9" fill="currentColor" opacity="0.7"/><line x1="44" y1="33" x2="44" y2="74" stroke="currentColor" strokeWidth="4" strokeLinecap="round"/><line x1="44" y1="48" x2="50" y2="38" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="44" y1="52" x2="28" y2="62" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="44" y1="74" x2="32" y2="124" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/><line x1="44" y1="74" x2="60" y2="120" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/><line x1="32" y1="124" x2="26" y2="148" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round"/><line x1="60" y1="120" x2="66" y2="148" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round"/></svg>,

    // ── HANDSPRING ──
    "Handspring": <svg viewBox="0 0 100 160" width="80" height="128">{pole}<circle cx="46" cy="132" r="9" fill="currentColor" opacity="0.7"/><line x1="46" y1="123" x2="46" y2="90" stroke="currentColor" strokeWidth="4" strokeLinecap="round"/><line x1="46" y1="106" x2="32" y2="96" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="46" y1="106" x2="60" y2="96" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="46" y1="90" x2="38" y2="28" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/><line x1="46" y1="90" x2="54" y2="28" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/></svg>,
    "Deadlift Handspring": <svg viewBox="0 0 100 160" width="80" height="128">{pole}<circle cx="46" cy="134" r="9" fill="currentColor" opacity="0.7"/><line x1="46" y1="125" x2="46" y2="90" stroke="currentColor" strokeWidth="4" strokeLinecap="round"/><line x1="46" y1="108" x2="30" y2="100" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="46" y1="108" x2="62" y2="100" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="46" y1="90" x2="44" y2="18" stroke="currentColor" strokeWidth="4.5" strokeLinecap="round"/></svg>,
    "Handspring Split": <svg viewBox="0 0 100 160" width="80" height="128">{pole}<circle cx="46" cy="132" r="9" fill="currentColor" opacity="0.7"/><line x1="46" y1="123" x2="46" y2="90" stroke="currentColor" strokeWidth="4" strokeLinecap="round"/><line x1="46" y1="106" x2="32" y2="97" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="46" y1="106" x2="60" y2="97" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="46" y1="90" x2="8" y2="54" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/><line x1="46" y1="90" x2="86" y2="54" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/></svg>,
    "Aerial Invert": <svg viewBox="0 0 100 160" width="80" height="128">{pole}<circle cx="46" cy="126" r="9" fill="currentColor" opacity="0.7"/><line x1="46" y1="117" x2="46" y2="84" stroke="currentColor" strokeWidth="4" strokeLinecap="round"/><line x1="46" y1="102" x2="30" y2="92" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="46" y1="102" x2="62" y2="92" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="46" y1="84" x2="34" y2="22" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/><line x1="46" y1="84" x2="58" y2="22" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/></svg>,

    // ── BASIC/PREP ──
    "Basic Invert Prep": <svg viewBox="0 0 100 160" width="80" height="128">{pole}<circle cx="44" cy="120" r="9" fill="currentColor" opacity="0.7"/><line x1="44" y1="111" x2="46" y2="80" stroke="currentColor" strokeWidth="4" strokeLinecap="round"/><line x1="46" y1="94" x2="30" y2="86" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="46" y1="94" x2="60" y2="86" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="46" y1="80" x2="34" y2="44" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/><line x1="46" y1="80" x2="54" y2="44" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/></svg>,
    "Shoulder Mount Prep": <svg viewBox="0 0 100 160" width="80" height="128">{pole}<circle cx="46" cy="124" r="9" fill="currentColor" opacity="0.7"/><line x1="46" y1="115" x2="46" y2="84" stroke="currentColor" strokeWidth="4" strokeLinecap="round"/><line x1="46" y1="100" x2="50" y2="88" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="46" y1="100" x2="38" y2="90" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="46" y1="84" x2="44" y2="38" stroke="currentColor" strokeWidth="4" strokeLinecap="round"/><line x1="44" y1="38" x2="36" y2="20" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/><line x1="44" y1="38" x2="54" y2="20" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/></svg>,
    "Pole Squat": <svg viewBox="0 0 100 160" width="80" height="128">{pole}<circle cx="44" cy="28" r="9" fill="currentColor" opacity="0.7"/><line x1="44" y1="37" x2="44" y2="64" stroke="currentColor" strokeWidth="4" strokeLinecap="round"/><line x1="44" y1="48" x2="50" y2="38" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="44" y1="52" x2="30" y2="48" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="44" y1="64" x2="24" y2="108" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/><line x1="44" y1="64" x2="62" y2="108" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/><line x1="24" y1="108" x2="20" y2="134" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><line x1="62" y1="108" x2="64" y2="134" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/></svg>,
  };

  return byName[name] || (
    <svg viewBox="0 0 100 160" width="80" height="128">
      {pole}
      <circle cx="44" cy="30" r="9" fill="currentColor" opacity="0.7"/>
      <line x1="44" y1="39" x2="44" y2="76" stroke="currentColor" strokeWidth="4" strokeLinecap="round"/>
      <line x1="44" y1="52" x2="50" y2="42" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/>
      <line x1="44" y1="55" x2="30" y2="52" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/>
      <line x1="44" y1="76" x2="36" y2="130" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/>
      <line x1="44" y1="76" x2="54" y2="128" stroke="currentColor" strokeWidth="3.5" strokeLinecap="round"/>
    </svg>
  );
}

export default function App() {
  const [lvl, setLvl] = useState("all");
  const [card, setCard] = useState(null);
  const [flipped, setFlipped] = useState(false);
  const [statuses, setStatuses] = useState({});
  const [used, setUsed] = useState([]);

  const pool = ALL.filter(c => lvl === "all" || c.level === lvl);
  const remaining = pool.filter(c => !statuses[c.name]);
  const known = Object.values(statuses).filter(v => v === "known").length;
  const review = Object.values(statuses).filter(v => v === "review").length;

  function draw() {
    const avail = remaining.filter(c => c !== card);
    if (!avail.length) return;
    const pick = avail[Math.floor(Math.random() * avail.length)];
    setCard(pick);
    setFlipped(false);
  }

  function mark(s) {
    if (!card) return;
    setStatuses(prev => ({...prev, [card.name]: s}));
    const avail = remaining.filter(c => c.name !== card.name);
    if (avail.length) {
      const pick = avail[Math.floor(Math.random() * avail.length)];
      setCard(pick);
      setFlipped(false);
    } else {
      setCard(null);
    }
  }

  function resetDeck() {
    setStatuses({});
    setCard(null);
    setFlipped(false);
  }

  const lc = card ? levelColor[card.level] : null;

  return (
    <div style={{padding:"1rem 0", fontFamily:"var(--font-sans)", maxWidth:460, margin:"0 auto"}}>

      {/* Level filter */}
      <div style={{display:"flex", gap:8, flexWrap:"wrap", marginBottom:"1.2rem"}}>
        {[["all","Tutti i livelli"],["beg","Principiante"],["int","Intermedio"],["adv","Avanzato"]].map(([v,l]) => (
          <button key={v} onClick={() => { setLvl(v); setCard(null); setFlipped(false); setStatuses({}); }}
            style={{padding:"6px 14px", borderRadius:20, border:"0.5px solid", borderColor: lvl===v ? "var(--color-border-primary)" : "var(--color-border-secondary)",
              background: lvl===v ? "var(--color-background-secondary)" : "var(--color-background-primary)",
              color: lvl===v ? "var(--color-text-primary)" : "var(--color-text-secondary)",
              fontWeight: lvl===v ? 500 : 400, fontSize:13, cursor:"pointer"}}>
            {l}
          </button>
        ))}
      </div>

      {/* Deck visual */}
      {!card && (
        <div style={{display:"flex", flexDirection:"column", alignItems:"center", gap:16, marginBottom:"1.5rem"}}>
          <div style={{position:"relative", width:200, height:130}} onClick={remaining.length ? draw : null}>
            {[{r:-3,tx:-4,ty:4},{r:1.5,tx:3,ty:2},{r:0,tx:0,ty:0}].map((s,i) => (
              <div key={i} style={{position:"absolute", width:200, height:130,
                borderRadius:"var(--border-radius-lg)", border:"0.5px solid var(--color-border-secondary)",
                background: i===2 ? "var(--color-background-primary)" : "var(--color-background-secondary)",
                transform:`rotate(${s.r}deg) translate(${s.tx}px,${s.ty}px)`,
                display:"flex", alignItems:"center", justifyContent:"center"}}>
                {i===2 && (
                  <div style={{textAlign:"center"}}>
                    <div style={{fontSize:14, fontWeight:500, color:"var(--color-text-primary)"}}>Mazzo</div>
                    <div style={{fontSize:12, color:"var(--color-text-tertiary)", marginTop:2}}>{remaining.length} carte rimaste</div>
                  </div>
                )}
              </div>
            ))}
          </div>
          <button onClick={draw} disabled={!remaining.length}
            style={{padding:"12px 40px", borderRadius:"var(--border-radius-lg)",
              border:"0.5px solid var(--color-border-primary)", background:"var(--color-background-primary)",
              cursor: remaining.length ? "pointer" : "default", fontSize:15, fontWeight:500,
              color:"var(--color-text-primary)", opacity: remaining.length ? 1 : 0.4}}>
            {remaining.length ? "Estrai una carta" : "Mazzo esaurito!"}
          </button>
          {!remaining.length && (
            <button onClick={resetDeck} style={{fontSize:13, color:"var(--color-text-secondary)",
              background:"none", border:"none", cursor:"pointer", textDecoration:"underline"}}>
              Ricomincia
            </button>
          )}
        </div>
      )}

      {/* Card */}
      {card && (
        <div style={{marginBottom:"1rem", animation:"slideUp .3s ease"}}>
          <style>{`@keyframes slideUp{from{opacity:0;transform:translateY(14px)}to{opacity:1;transform:translateY(0)}}`}</style>

          {/* Front */}
          {!flipped ? (
            <div onClick={() => setFlipped(true)} style={{borderRadius:"var(--border-radius-lg)",
              border:"0.5px solid var(--color-border-tertiary)", background:"var(--color-background-primary)",
              padding:"1.5rem", cursor:"pointer", textAlign:"center"}}>
              <div style={{display:"flex", gap:6, justifyContent:"center", marginBottom:10}}>
                <span style={{fontSize:11, padding:"3px 10px", borderRadius:10, fontWeight:500,
                  background:lc.bg, color:lc.text}}>{levelLabel[card.level]}</span>
                <span style={{fontSize:11, padding:"3px 10px", borderRadius:10,
                  background:"var(--color-background-secondary)", color:"var(--color-text-secondary)"}}>{card.cat}</span>
              </div>
              <div style={{fontSize:22, fontWeight:500, color:"var(--color-text-primary)", marginBottom:16}}>{card.name}</div>
              <div style={{display:"flex", justifyContent:"center", color:"var(--color-text-secondary)", marginBottom:12}}>
                <PoleIcon cat={card.cat} />
              </div>
              <div style={{fontSize:12, color:"var(--color-text-tertiary)"}}>Tocca per vedere i dettagli</div>
            </div>
          ) : (
            <div onClick={() => setFlipped(false)} style={{borderRadius:"var(--border-radius-lg)",
              border:"0.5px solid var(--color-border-tertiary)", background:"var(--color-background-primary)",
              padding:"1.5rem", cursor:"pointer"}}>
              <div style={{display:"flex", gap:6, marginBottom:10}}>
                <span style={{fontSize:11, padding:"3px 10px", borderRadius:10, fontWeight:500,
                  background:lc.bg, color:lc.text}}>{levelLabel[card.level]}</span>
                <span style={{fontSize:11, padding:"3px 10px", borderRadius:10,
                  background:"var(--color-background-secondary)", color:"var(--color-text-secondary)"}}>{card.cat}</span>
              </div>
              <div style={{fontSize:20, fontWeight:500, color:"var(--color-text-primary)", marginBottom:12}}>{card.name}</div>
              <div style={{fontSize:14, color:"var(--color-text-primary)", lineHeight:1.7, marginBottom:10}}>{card.desc}</div>
              <div style={{fontSize:13, color:"var(--color-text-secondary)", fontStyle:"italic"}}>Tip: {card.tip}</div>
              <div style={{fontSize:12, color:"var(--color-text-tertiary)", marginTop:10}}>Tocca per girare</div>
            </div>
          )}

          {/* Mark buttons */}
          <div style={{display:"flex", gap:10, marginTop:10}}>
            <button onClick={() => mark("review")} style={{flex:1, padding:9, borderRadius:"var(--border-radius-md)",
              border:"0.5px solid #D85A30", cursor:"pointer", fontSize:13,
              background:"var(--color-background-primary)", color:"#D85A30"}}>Da ripassare</button>
            <button onClick={() => { setCard(null); setFlipped(false); }} style={{flex:1, padding:9, borderRadius:"var(--border-radius-md)",
              border:"0.5px solid var(--color-border-secondary)", cursor:"pointer", fontSize:13,
              background:"var(--color-background-primary)", color:"var(--color-text-secondary)"}}>Altra carta</button>
            <button onClick={() => mark("known")} style={{flex:1, padding:9, borderRadius:"var(--border-radius-md)",
              border:"0.5px solid #1D9E75", cursor:"pointer", fontSize:13,
              background:"var(--color-background-primary)", color:"#1D9E75"}}>La so!</button>
          </div>
        </div>
      )}

      {/* Stats */}
      <div style={{display:"flex", gap:8, justifyContent:"center", marginTop: card ? 0 : "0.5rem"}}>
        {[["statKnown", known, "Sapute"],["statReview", review, "Da ripassare"],["statLeft", remaining.length, "Rimaste"]].map(([id,n,l]) => (
          <div key={id} style={{flex:1, background:"var(--color-background-secondary)", borderRadius:"var(--border-radius-md)",
            padding:"8px 12px", textAlign:"center"}}>
            <div style={{fontSize:20, fontWeight:500, color:"var(--color-text-primary)"}}>{n}</div>
            <div style={{fontSize:11, color:"var(--color-text-secondary)"}}>{l}</div>
          </div>
        ))}
      </div>

      {/* Reset */}
      {(known+review > 0) && (
        <div style={{textAlign:"center", marginTop:12}}>
          <button onClick={resetDeck} style={{fontSize:12, color:"var(--color-text-tertiary)",
            background:"none", border:"none", cursor:"pointer", textDecoration:"underline"}}>
            Ricomincia mazzo
          </button>
        </div>
      )}
    </div>
  );
}
